### ISSUE TITLE
Error when trying to install on mac

### ISSUE THREAD

**Issue by shykovart** [figma-plus/installer#15] opened 2019-05-10 12:01 UTC
```
Error: EACCES: permission denied, copyfile '/Applications/Figma.app/Contents/Resources/app.asar' -> '/Applications/Figma.app/Contents/Resources/app.asar.bk'
    at Object.fs.copyFileSync (original-fs.js:2026:3)
    at writePacked (/Applications/Figma Plus.app/Contents/Resources/app.asar/renderer.js:281:18)
    at /Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/asar.js:157:18
    at writeFileListToStream (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:42:10)
    at ReadStream.<anonymous> (/Applications/Figma Plus.app/Contents/Resources/app.asar/node_modules/asar/lib/disk.js:37:16)
    at ReadStream.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

---

Figma Plus 1.0.0
Electron 3.0.9
darwin 18.5.0
Locale: en-US

**Comment by Briix** [comment] 2019-05-13 10:55
Seems to be a duplicate of https://github.com/figma-plus/installer/issues/14. You can find more information in the other issue :)

**Closed** 2019-05-13 10:57 UTC
